### ISSUE TITLE
"get_data.rb:41:in `sort': comparison of String with nil failed (ArgumentError)" when used against chef server 12.0.8.

### ISSUE THREAD

**Issue by grahamja** [nsdavidson/chef-cleanup#3]
[chef-cleanup][CHEFDK][jsong]:chef exec ruby get_data.rb --orgs gap --knife-config ~/chef_environments/devchef12/knife.rb
Processing organization gap...
get_data.rb:41:in `sort': comparison of String with nil failed (ArgumentError)
	from get_data.rb:41:in `block in get_unused_cookbooks'
	from get_data.rb:38:in `each'
	from get_data.rb:38:in `get_unused_cookbooks'
	from get_data.rb:109:in `block in <main>'
	from get_data.rb:80:in `each'
	from get_data.rb:80:in `<main>'

**Comment by nsdavidson** [comment]
@grahamja I believe PR #4 should resolve your issue.  Please update from master and give it another try.  Let us know if it doesn't!
